import type { ProgramDefinition } from './types';

export const FINITE_COUNTER_PROGRAM: ProgramDefinition = {
  id: 'finite-counter',
  name: 'PROG α: FINITE COUNTER [i < 5]',
  shortTag: 'PROG α',
  description: 'Deterministic bounded counter that monotonically increments until condition i < 5 fails, reaching HALT in exactly 5 iterations.',
  theoreticalBehavior: 'terminating',
  expectedSteps: 5,
  entryNodeId: 'q0_start',
  initialVariables: { i: 0 },
  instructions: {
    q0_start: {
      id: 'q0_start',
      type: 'SET',
      variable: 'i',
      value: 0,
      next: 'q_eval',
      label: 'SET i = 0',
    },
    q_eval: {
      id: 'q_eval',
      type: 'CHECK',
      variable: 'i',
      op: '<',
      threshold: 5,
      onTrue: 'q_inc',
      onFalse: 'q_halt',
      label: 'CHECK (i < 5)',
    },
    q_inc: {
      id: 'q_inc',
      type: 'INCREMENT',
      variable: 'i',
      next: 'q_eval',
      label: 'i = i + 1',
    },
    q_halt: {
      id: 'q_halt',
      type: 'HALT',
      label: 'HALT (q_accept)',
    },
  },
  nodes: [
    {
      id: 'q0_start',
      label: 'q₀ // ENTRY',
      sublabel: 'SET i = 0',
      type: 'init',
      x: 350,
      y: 40,
    },
    {
      id: 'q_eval',
      label: 'q_eval // BRANCH',
      sublabel: 'CHECK (i < 5)',
      type: 'check',
      x: 350,
      y: 170,
    },
    {
      id: 'q_inc',
      label: 'q_loop // ACC_MUTATE',
      sublabel: 'i = i + 1',
      type: 'mutate',
      x: 180,
      y: 330,
    },
    {
      id: 'q_halt',
      label: 'q_accept // TERMINAL',
      sublabel: 'HALT [0]',
      type: 'halt',
      x: 520,
      y: 330,
    },
  ],
  edges: [
    {
      id: 'e-start-eval',
      source: 'q0_start',
      target: 'q_eval',
      label: 'INIT',
      type: 'default',
    },
    {
      id: 'e-eval-inc',
      source: 'q_eval',
      target: 'q_inc',
      label: 'YES [i < 5]',
      type: 'condition-true',
    },
    {
      id: 'e-inc-eval',
      source: 'q_inc',
      target: 'q_eval',
      label: 'LOOP BACK',
      type: 'loopback',
    },
    {
      id: 'e-eval-halt',
      source: 'q_eval',
      target: 'q_halt',
      label: 'NO [i ≥ 5]',
      type: 'condition-false',
    },
  ],
};

export const INFINITE_LOOP_PROGRAM: ProgramDefinition = {
  id: 'infinite-loop',
  name: 'PROG β: UNBOUNDED LOOP [∞]',
  shortTag: 'PROG β',
  description: 'Deterministic program lacking a program-level exit predicate. Continues incrementing indefinitely without reaching a terminal accept state.',
  theoreticalBehavior: 'non-terminating',
  entryNodeId: 'q0_start',
  initialVariables: { i: 0 },
  instructions: {
    q0_start: {
      id: 'q0_start',
      type: 'SET',
      variable: 'i',
      value: 0,
      next: 'q_loop',
      label: 'SET i = 0',
    },
    q_loop: {
      id: 'q_loop',
      type: 'INCREMENT',
      variable: 'i',
      next: 'q_jump',
      label: 'i = i + 1',
    },
    q_jump: {
      id: 'q_jump',
      type: 'JUMP',
      target: 'q_loop',
      label: 'JUMP q_loop',
    },
  },
  nodes: [
    {
      id: 'q0_start',
      label: 'q₀ // ENTRY',
      sublabel: 'SET i = 0',
      type: 'init',
      x: 350,
      y: 60,
    },
    {
      id: 'q_loop',
      label: 'q_spin // CYCLE',
      sublabel: 'i = i + 1',
      type: 'mutate',
      x: 230,
      y: 220,
    },
    {
      id: 'q_jump',
      label: 'q_recurse // UNBOUNDED',
      sublabel: 'GOTO q_spin',
      type: 'loop',
      x: 470,
      y: 220,
    },
  ],
  edges: [
    {
      id: 'e-start-loop',
      source: 'q0_start',
      target: 'q_loop',
      label: 'START',
      type: 'default',
    },
    {
      id: 'e-loop-jump',
      source: 'q_loop',
      target: 'q_jump',
      label: 'NEXT',
      type: 'default',
    },
    {
      id: 'e-jump-loop',
      source: 'q_jump',
      target: 'q_loop',
      label: 'INFINITE CYCLE',
      type: 'loopback',
    },
  ],
};

export const INPUT_DEPENDENT_PROGRAM = (n: number = 8): ProgramDefinition => ({
  id: 'input-dependent',
  name: `PROG γ: INPUT-DEPENDENT [i < ${n}]`,
  shortTag: 'PROG γ',
  description: `Parameterized counter terminating after exactly ${n} iterations based on dynamic register input parameter N=${n}.`,
  theoreticalBehavior: 'input-dependent',
  expectedSteps: n,
  entryNodeId: 'q0_start',
  initialVariables: { i: 0, N: n },
  instructions: {
    q0_start: {
      id: 'q0_start',
      type: 'SET',
      variable: 'i',
      value: 0,
      next: 'q_eval',
      label: 'SET i = 0',
    },
    q_eval: {
      id: 'q_eval',
      type: 'CHECK',
      variable: 'i',
      op: '<',
      threshold: n,
      onTrue: 'q_inc',
      onFalse: 'q_halt',
      label: `CHECK (i < ${n})`,
    },
    q_inc: {
      id: 'q_inc',
      type: 'INCREMENT',
      variable: 'i',
      next: 'q_eval',
      label: 'i = i + 1',
    },
    q_halt: {
      id: 'q_halt',
      type: 'HALT',
      label: 'HALT (q_accept)',
    },
  },
  nodes: [
    {
      id: 'q0_start',
      label: 'q₀ // ENTRY',
      sublabel: `SET i = 0, N = ${n}`,
      type: 'init',
      x: 350,
      y: 40,
    },
    {
      id: 'q_eval',
      label: 'q_eval // BRANCH',
      sublabel: `CHECK (i < ${n})`,
      type: 'check',
      x: 350,
      y: 170,
    },
    {
      id: 'q_inc',
      label: 'q_loop // ACC_MUTATE',
      sublabel: 'i = i + 1',
      type: 'mutate',
      x: 180,
      y: 330,
    },
    {
      id: 'q_halt',
      label: 'q_accept // TERMINAL',
      sublabel: 'HALT [0]',
      type: 'halt',
      x: 520,
      y: 330,
    },
  ],
  edges: [
    {
      id: 'e-start-eval',
      source: 'q0_start',
      target: 'q_eval',
      label: 'INIT',
      type: 'default',
    },
    {
      id: 'e-eval-inc',
      source: 'q_eval',
      target: 'q_inc',
      label: `YES [i < ${n}]`,
      type: 'condition-true',
    },
    {
      id: 'e-inc-eval',
      source: 'q_inc',
      target: 'q_eval',
      label: 'LOOP BACK',
      type: 'loopback',
    },
    {
      id: 'e-eval-halt',
      source: 'q_eval',
      target: 'q_halt',
      label: `NO [i ≥ ${n}]`,
      type: 'condition-false',
    },
  ],
});
